import type { Donation, Ngo, Provider } from "./types";

export const PROVIDERS: Provider[] = [
  {
    id: "p1",
    name: "Green Leaf Café",
    type: "Café",
    location: "Jubilee Hills",
    lat: 17.43,
    lng: 78.41,
    verified: true,
    reliability: 0.92,
  },
  {
    id: "p2",
    name: "Sunrise Bakery",
    type: "Bakery",
    location: "Banjara Hills",
    lat: 17.41,
    lng: 78.44,
    verified: true,
    reliability: 0.88,
  },
  {
    id: "p3",
    name: "Urban Feast Caterers",
    type: "Caterer",
    location: "Madhapur",
    lat: 17.45,
    lng: 78.39,
    verified: true,
    reliability: 0.95,
  },
  {
    id: "p4",
    name: "FreshMart Supermarket",
    type: "Supermarket",
    location: "Gachibowli",
    lat: 17.44,
    lng: 78.35,
    verified: true,
    reliability: 0.81,
  },
  {
    id: "p5",
    name: "City Harvest Hotel",
    type: "Hotel",
    location: "Somajiguda",
    lat: 17.42,
    lng: 78.46,
    verified: true,
    reliability: 0.9,
  },
];

export const NGOS: Ngo[] = [
  {
    id: "n1",
    name: "Hope Foundation",
    location: "Jubilee Hills",
    lat: 17.44,
    lng: 78.42,
    verified: true,
    capacityMeals: 60,
    acceptedCategories: ["Cooked meals", "Bakery", "Fruits", "Vegetables", "Packaged food"],
    pickupWindowMinutes: 30,
    reliability: 0.94,
    peopleServed: 4820,
  },
  {
    id: "n2",
    name: "Helping Hands Community",
    location: "Ameerpet",
    lat: 17.44,
    lng: 78.45,
    verified: true,
    capacityMeals: 120,
    acceptedCategories: ["Cooked meals", "Vegetables", "Dairy", "Packaged food"],
    pickupWindowMinutes: 60,
    reliability: 0.87,
    peopleServed: 7310,
  },
  {
    id: "n3",
    name: "Seva Meals",
    location: "Kukatpally",
    lat: 17.49,
    lng: 78.4,
    verified: true,
    capacityMeals: 200,
    acceptedCategories: ["Cooked meals", "Bakery", "Fruits", "Vegetables", "Dairy", "Other"],
    pickupWindowMinutes: 90,
    reliability: 0.91,
    peopleServed: 12440,
  },
  {
    id: "n4",
    name: "Community Care Centre",
    location: "Secunderabad",
    lat: 17.44,
    lng: 78.5,
    verified: true,
    capacityMeals: 45,
    acceptedCategories: ["Bakery", "Fruits", "Packaged food", "Dairy"],
    pickupWindowMinutes: 45,
    reliability: 0.78,
    peopleServed: 2130,
  },
];

const hoursFromNow = (h: number) => new Date(Date.now() + h * 3600_000).toISOString();
const hoursAgo = (h: number) => new Date(Date.now() - h * 3600_000).toISOString();

export const SEED_DONATIONS: Donation[] = [
  {
    id: "d1001",
    providerId: "p2",
    foodName: "Assorted breads & croissants",
    category: "Bakery",
    quantity: "50 items",
    servings: 50,
    preparedAt: hoursAgo(6),
    consumeBy: hoursFromNow(8),
    pickupLocation: "Sunrise Bakery, Banjara Hills",
    pickupWindow: "Today 18:00 – 20:00",
    condition: "Fresh, packed",
    createdAt: hoursAgo(1),
    status: "AI Matched",
    matchedNgoId: "n1",
    matchScore: 92,
    matchReason:
      "Recommended because this NGO is 2.4 km away, currently has capacity for 50 meals, and can arrange pickup within 30 minutes.",
  },
  {
    id: "d1002",
    providerId: "p3",
    foodName: "Wedding buffet – veg biryani & curries",
    category: "Cooked meals",
    quantity: "12 trays",
    servings: 180,
    preparedAt: hoursAgo(3),
    consumeBy: hoursFromNow(4),
    pickupLocation: "Urban Feast Caterers, Madhapur",
    pickupWindow: "Today 21:00 – 22:30",
    condition: "Hot-held, covered",
    createdAt: hoursAgo(2),
    status: "Pickup Scheduled",
    matchedNgoId: "n3",
    matchScore: 88,
    matchReason:
      "Seva Meals has 200 meal capacity, accepts cooked meals and can collect within 90 minutes.",
  },
  {
    id: "d1003",
    providerId: "p4",
    foodName: "Surplus fruit crates",
    category: "Fruits",
    quantity: "8 crates",
    servings: 90,
    preparedAt: hoursAgo(20),
    consumeBy: hoursFromNow(30),
    pickupLocation: "FreshMart, Gachibowli",
    pickupWindow: "Tomorrow 09:00 – 12:00",
    condition: "Chilled",
    createdAt: hoursAgo(22),
    status: "Collected",
    matchedNgoId: "n2",
    matchScore: 84,
    matchReason: "Helping Hands has spare capacity and an active fruit distribution drive.",
  },
  {
    id: "d1004",
    providerId: "p1",
    foodName: "Sandwiches & salad bowls",
    category: "Cooked meals",
    quantity: "35 packs",
    servings: 35,
    preparedAt: hoursAgo(30),
    consumeBy: hoursAgo(6),
    pickupLocation: "Green Leaf Café, Jubilee Hills",
    pickupWindow: "Yesterday 19:00 – 20:00",
    condition: "Chilled, sealed",
    createdAt: hoursAgo(34),
    status: "Completed",
    matchedNgoId: "n1",
    matchScore: 95,
    matchReason: "Closest verified NGO with immediate pickup capability.",
  },
  {
    id: "d1005",
    providerId: "p5",
    foodName: "Breakfast buffet surplus",
    category: "Cooked meals",
    quantity: "6 trays",
    servings: 70,
    preparedAt: hoursAgo(50),
    consumeBy: hoursAgo(40),
    pickupLocation: "City Harvest Hotel, Somajiguda",
    pickupWindow: "Yesterday 11:00 – 12:00",
    condition: "Hot-held",
    createdAt: hoursAgo(52),
    status: "Completed",
    matchedNgoId: "n2",
    matchScore: 90,
    matchReason: "Capacity match and 15-minute travel distance.",
  },
  {
    id: "d1006",
    providerId: "p4",
    foodName: "Packaged milk & yoghurt",
    category: "Dairy",
    quantity: "120 units",
    servings: 120,
    preparedAt: hoursAgo(10),
    consumeBy: hoursFromNow(48),
    pickupLocation: "FreshMart, Gachibowli",
    pickupWindow: "Today 16:00 – 19:00",
    condition: "Chilled, sealed",
    createdAt: hoursAgo(5),
    status: "Listed",
  },
];
